{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92aec6d8-7ad9-4c20-ae69-322a7a86366d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Importa a classe base abstrata e o decorador pra métodos abstrados \n",
    "from abc import ABC, abstractmethod\n",
    "\n",
    "#Importa classe datetime para registrar data e hora das transações\n",
    "from datetime import datetime\n",
    "\n",
    "#Importa execeção personalizada para saldo insuficiente\n",
    "from utilitarios.exceptions import SaldoInsuficienteError\n",
    "\n",
    "#Define a classe abstrata Conta, que server como base para outros tipos de contas\n",
    "class Conta(ABC):\n",
    "    \"\"\"\n",
    "    Classe base abstrata para contas bancarias.\n",
    "    Demonstra Herança e Encapsulamento.\n",
    "    \"\"\"\n",
    "\n",
    "    #Atributos de classe que calcula quantas contas foram criadas\n",
    "    _total_contas = 0\n",
    "\n",
    "    #Construtor da classe\n",
    "    def __init__(self, numero: int, cliente):\n",
    "\n",
    "        #Numero da conta (atributo protegido)\n",
    "        self.__numero = numero\n",
    "\n",
    "        #Saldo da conta, inicializado em em 0.0 (atributo protegido)\n",
    "        self._saldo = 0.0\n",
    "\n",
    "        #Referenicia ao cliente dono da conta\n",
    "        self._cliente = cliente\n",
    "\n",
    "        #Lista para armazenar historico de transações\n",
    "        self.historico = []\n",
    "\n",
    "        #Incrementa o total de contas criadas\n",
    "        Conta._total_constas += 1\n",
    "\n",
    "    #Método para acessar o saldo de forma controlada\n",
    "    @property\n",
    "    def saldo(self):\n",
    "        \n",
    "        \"\"\"Getter para o saldo, permite acesso controlado.\"\"\"\n",
    "\n",
    "        return self._saldo\n",
    "\n",
    "    #Método de classe par aconsultar o numero toral de contas\n",
    "    @classmethod\n",
    "    def get_total_contas(cls):\n",
    "\n",
    "        \"\"\"Método de classe para obter o numero total de contas\"\"\"\n",
    "\n",
    "        return cls._total_contas\n",
    "\n",
    "    #Método para realizar depositos\n",
    "    def depositar(self, valor: float):\n",
    "\n",
    "        #Adicionar um valor ao saldo da conta\n",
    "        if valor > 0:\n",
    "\n",
    "            #Incrementa o saldo \n",
    "            self._saldo += valor\n",
    "\n",
    "            #Registra a transação no historico com data e hora\n",
    "            self._historico.append((datetime.now(), f\"Depósito de R${valor:.2f}\"))\n",
    "            print(f\"Depósito de R${valor:.2f} realizado com sucesso.\")\n",
    "        else:\n",
    "            print(\"Valor de dpósito inválido.\")\n",
    "\n",
    "    #Metodo abstrado que deve ser implementado pelas subclasses\n",
    "    @abstractmethod\n",
    "    def sacar(self, valor: float):\n",
    "        \n",
    "        \"\"\"Método abstrado para sacar um valor. Deve se implementado pelas subclasses\"\"\"\n",
    "\n",
    "        pass\n",
    "\n",
    "    #Metodo para exibir o extrato da conta\n",
    "    def estrato(self):\n",
    "\n",
    "        \"\"\" Exibe o estrato da conta \"\"\"\n",
    "        print(f\"\\n=== Extrato da Conta Nº {self._numero} ===\")\n",
    "        print(f\"Cliente: {self._cliente.nome}\")\n",
    "        print(f\"Saldo atual: R${self._saldo:.2f}\")\n",
    "        print(\"Histórico de tansações.\")\n",
    "\n",
    "        # Percorre o histórico e exibe cada transação\n",
    "        for data, transacao in self._historico:\n",
    "            print(f\" {data.strtime('%d/%m/%Y %H/;%M:%S')}: {transacao}\")\n",
    "        print(\"______________________________________\\n\")\n",
    "\n",
    "#Define a subclasse ContaCorrete\n",
    "class ContaCorrente(Conta):\n",
    "\n",
    "    \"\"\"\n",
    "    Subclasse que representa um conta corrente.\n",
    "    Demonstra Polimorfismo ao sobescrever o método sacar\n",
    "    \"\"\"\n",
    "\n",
    "    #Construtor com limite padrao do cheque especial\n",
    "    def __init__(self, numero: int, cliente, limite: float = 500.0):\n",
    "\n",
    "        #Chama o construtor da classe base\n",
    "        super().__init__(numero, cliente)\n",
    "\n",
    "        #Define o limete de cheque especial\n",
    "        self.limite = limite\n",
    "\n",
    "    #Implementacao do método sacar com cheque especial\n",
    "    def sacar(self, valor: float):\n",
    "\n",
    "        \"\"\"Permite saque utilizando o saldo da conta mais o limite (cheque especial).\"\"\"\n",
    "\n",
    "        if valor <= 0:\n",
    "            print(\"Valor de saque inválido\")\n",
    "            return\n",
    "\n",
    "        #Calcula o saldo disponivel (saldo + limite)\n",
    "        saldo._disponivel = self._saldo + self.limite\n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
